// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "d29726d1-fce4-4d45-a998-c5f001646d48";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onDev1BChange();
void onDev2BChange();
void onDev3BChange();
void onDev4BChange();

CloudLight dev1B;
CloudLight dev2B;
CloudLight dev3B;
CloudLight dev4B;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(dev1B, READWRITE, ON_CHANGE, onDev1BChange);
  ArduinoCloud.addProperty(dev2B, READWRITE, ON_CHANGE, onDev2BChange);
  ArduinoCloud.addProperty(dev3B, READWRITE, ON_CHANGE, onDev3BChange);
  ArduinoCloud.addProperty(dev4B, READWRITE, ON_CHANGE, onDev4BChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
